import type {
  AiStatus,
  Email,
  GmailStatus,
  JobApplication,
  WorkspaceSnapshot,
} from '../domain/models';
export const jobFixture: JobApplication = {
  id: 'job-northstar',
  company: 'Northstar Labs',
  role: 'Frontend Engineer',
  location: 'Stockholm',
  jobUrl: '',
  source: 'Manual',
  appliedAt: '2026-09-01',
  currentStage: 'applied',
  nextAction: null,
  nextActionDueAt: null,
  notes: '',
  archived: false,
  stageManuallySet: false,
  createdAt: '2026-09-01T10:00:00Z',
  updatedAt: '2026-09-01T10:00:00Z',
};
export const emailFixture: Email = {
  id: 'email-interview',
  gmailMessageId: 'fixture-interview',
  gmailThreadId: 'fixture-thread-northstar',
  gmailAccountId: null,
  remoteDeleted: false,
  senderName: 'Mira at Northstar Labs',
  senderEmail: 'mira@northstar.example',
  recipients: ['alex@candidate.example'],
  subject: 'Interview invitation — Frontend Engineer at Northstar Labs',
  snippet: 'Please send your availability.',
  bodyText:
    'Hi Alex,\nPlease send your availability for an interview by 2026-09-10.\nCompany: Northstar Labs\nRole: Frontend Engineer',
  receivedAt: '2026-09-07T09:00:00Z',
  contentHash: 'fictional-fingerprint',
  category: 'interview',
  classificationConfidence: 0.96,
  classificationSource: 'local_rules',
  classifiedAt: '2026-09-08T10:00:00Z',
  requiresAction: true,
  suggestedAction: 'Send your interview availability',
  createdAt: '2026-09-08T10:00:00Z',
  updatedAt: '2026-09-08T10:00:00Z',
  isJobRelated: true,
  reasoningCode: 'interview_request',
  extractedCompany: 'Northstar Labs',
  extractedRole: 'Frontend Engineer',
  suggestedStage: 'interview',
  eventType: 'interview_requested',
  deadline: '2026-09-10',
  manualOverride: false,
  ignored: false,
  actionCompleted: false,
};
export function gmailStatus(overrides: Partial<GmailStatus> = {}): GmailStatus {
  return {
    configured: false,
    connected: false,
    credentialStoreAvailable: true,
    clientId: null,
    accountEmail: null,
    phase: 'not_configured',
    lastSyncedAt: null,
    lastError: null,
    processed: 0,
    total: 0,
    imported: 0,
    skipped: 0,
    failed: 0,
    ...overrides,
  };
}
export function workspace(overrides: Partial<WorkspaceSnapshot> = {}): WorkspaceSnapshot {
  return {
    applications: [],
    emails: [],
    events: [],
    links: [],
    databasePath: 'C:\\FictionalTests\\mailview.sqlite3',
    settings: {
      syncEmailLimit: 500,
      localConfidenceAcceptThreshold: 0.9,
      localConfidenceGeminiThreshold: 0.5,
      aiMode: 'off',
    },
    ...overrides,
  };
}
export function aiStatus(overrides: Partial<AiStatus> = {}): AiStatus {
  return {
    configured: false,
    credentialStoreAvailable: true,
    settings: { model: 'gemini-2.5-flash-lite', maxRequestsPerRun: 50 },
    usage: { requests: 0, succeeded: 0, inputTokens: 0, outputTokens: 0, cacheHits: 0 },
    running: false,
    processed: 0,
    total: 0,
    applied: 0,
    cacheHits: 0,
    requests: 0,
    lastError: null,
    lastMessage: null,
    ...overrides,
  };
}
